### ISSUE TITLE
奇游加速器，想要app内使用您的计算器功能

### ISSUE THREAD

**Issue by qeeyou007** [dellbeat/NshmCalculator#1]
你好，我们是奇游加速器，看到您的开源计算器功能，我们想在app内上线该功能给更多的逆水寒用户使用，想要征得您的授权。

**Comment by dellbeat** [comment]
您好，看到了您提的Issue，能收到授权请求很意外，出于稳妥考虑，授权前有细节想要沟通一下
第一个是二次开发可行性，如果贵司有了解.Net技术栈的人员应该没问题
第二个是我的数据也是向各位原作者取得的非商用授权的，因为当时没有考虑过会有贵司这种请求授权的情况，可能需要贵司通过在B站/小红书的机构账号向原来的作者取得数据使用授权

如果Github上交流不太方便可以发送其他联系方式

**Comment by qeeyou007** [comment]
因涉及到的作者较多，不知您是否可以帮助我们将我们的联系方式发送给他们或将他们的联系方式发送给我们呢？平台留言或许不能得到及时的回应。
万分感谢，我的微信：in_Jiang
------------------------------------------------------------------
发件人：dellbeat ***@***.***>
发送时间：2024年11月29日(星期五) 15:35
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [dellbeat/NshmCalculator] 奇游加速器，想要app内使用您的计算器功能 (Issue #1)
您好，看到了您提的Issue，能收到授权请求很意外，出于稳妥考虑，授权前有细节想要沟通一下
 第一个是二次开发可行性，如果贵司有了解.Net技术栈的人员应该没问题
 第二个是我的数据也是向各位原作者取得的非商用授权的，因为当时没有考虑过会有贵司这种请求授权的情况，可能需要贵司通过在B站/小红书的机构账号向原来的作者取得数据使用授权
如果Github上交流不太方便可以发送其他联系方式

**Comment by dellbeat** [comment]
可以的 稍后联系您微信

**Comment by qeeyou007** [comment]
十分感谢！！
------------------------------------------------------------------
发件人：dellbeat ***@***.***>
发送时间：2024年11月29日(星期五) 15:46
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [dellbeat/NshmCalculator] 奇游加速器，想要app内使用您的计算器功能 (Issue #1)
可以的 稍后联系您微信

**Comment by dellbeat** [comment]
经沟通，已让奇游加速器的工作人员向两位老师征询数据授权，本Issue关闭
